# Generated by Django 3.1.7 on 2021-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='park',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car_number', models.CharField(max_length=100)),
                ('time_in', models.DateTimeField()),
                ('car_slot', models.IntegerField()),
            ],
        ),
    ]
