# Generated by Django 3.1.7 on 2021-04-16 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 23, 21, 5, 69280)),
        ),
    ]
